version: "3.3"
services:
  rabbitmq:
    image: 'rabbitmq:3.12.2-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${TELEGRAM_SVC_RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${TELEGRAM_SVC_RABBIT_PASS}
